### ISSUE TITLE
How to define and run meta tasks

### ISSUE THREAD

**Issue by Merott** [ngbp/warlock#3]
Something that I haven't found to be mentioned in the docs, is how to define your own meta tasks as an end user of Warlock.

For example, if I wanted to alias `webapp-build` to just `b`, can I do that?

Also, I don't think the docs make it clear how to run individual tasks, for example just the **build** part of the default warlock task when using the web app spell. Although it's simple, and I could figure it out, I think it's such a common need that would make sense to be made clearer in the docs.

**Comment by joshdmiller** [comment]
> if I wanted to alias webapp-build to just b, can I do that?

Not yet, no. But this is a feature that should exist. You can fake it in a somewhat silly way, for now. Create a directory in your project to store plugins and create a file inside it with these contents:

``` js
// customizations.js
module.exports = function ( warlock ) {
  warlock.task.add( 'b', [ 'webapp-build' ] );
}
```

And then add this to your `warlock.json`:

``` json
{
  "plugins": [ "path/to/plugins/dir" ]
}
```

If you want to take a stab at adding some JSON-based functionality for this kind of thing, I'd be happy to accept a good PR.

> I don't think the docs make it clear how to run individual tasks... I think it's such a common need that would make sense to be made clearer in the docs.

You're right.

**Comment by Merott** [comment]
Well, how about that? #5

**Comment by Merott** [comment]
This one's answered, and I've submitted a [PR for the aliasing feature](https://github.com/ngbp/warlock/pull/5), so this issue can be closed.
